### ISSUE TITLE
Multiple chained component registrations are not supported

### ISSUE THREAD

**Issue by ipatalas** [ipatalas/ngComponentUtility#13]
Multiple chained component registrations are not supported as well so this:

```
angular.module("components", [])
    .component("test1", new Test1())
    .component("test2", new Test2());
```

will only capture last registration.

**Comment by ipatalas** [comment]
Split from #10

**Comment by stogle** [comment]
This is great! The extension now finds 68 components in my project, compared to 45 before.

**Comment by ipatalas** [comment]
Is this all of your components or still some of them missing?

**Comment by stogle** [comment]
I think that is all except those not found due to #14
