### ISSUE TITLE
Components are not searched recursively when using ES6 import

### ISSUE THREAD

**Issue by ipatalas** [ipatalas/ngComponentUtility#14]
At the moment it's only scanning one level deep.

**Comment by ipatalas** [comment]
Split from #10

**Comment by stogle** [comment]
@ipatalas I was looking forward to trying this but when I upgraded to the latest version I get an error when scanning components:

> [Extension Host] [ngComponents] HTML stats [files=136, glob=295 ms, parse=176 ms]
> extensionHost.ts:297 [Extension Host] [ngComponents] Controller stats [files=92, glob=160 ms, parse=463 ms, analyze=51 ms, total=674 ms]
> extensionHost.ts:297 [Extension Host] [ngComponents] Component stats [files=130, glob=207 ms, parse=46 ms, analyze=506 ms, total=759 ms]
> extensionHost.ts:297 [Extension Host] [ngComponents] Route stats [files=2, glob=161 ms, parse=5.01 ms, analyze=7.09 ms, total=173 ms]
> messageService.ts:125 Error refreshing components, check developer console
> e.doShow @ messageService.ts:125
> e.show @ messageService.ts:104
> t.showMessage @ mainThreadMessageService.ts:64
> n.Class.derive._oncancel @ winjs.base.raw.js:1638
> t.showMessage @ mainThreadMessageService.ts:34
> t.$showMessage @ mainThreadMessageService.ts:28
> e.handle @ abstractThreadService.ts:34
> s @ ipcRemoteCom.ts:275
> f @ ipcRemoteCom.ts:231
> _combinedTickCallback @ internal/process/next_tick.js:67
> _tickCallback @ internal/process/next_tick.js:98

Any ideas?

**Comment by stogle** [comment]
@ipatalas I got the extension running in debug mode and found the real error:

> TypeError: Cannot read property 'path' of undefined
>     at __dirname.constructor.loadComponents.components.forEach.c (c:\Git\ngComponentUtility\out\src\providers\memberCompletionProvider.js:11:66)
>     at Array.forEach (native)
>     at MemberCompletionProvider.__dirname.constructor.loadComponents (c:\Git\ngComponentUtility\out\src\providers\memberCompletionProvider.js:10:24)
>     at Object.<anonymous> (c:\Git\ngComponentUtility\out\src\extension.js:89:38)
>     at Generator.next (<anonymous>)
>     at fulfilled (c:\Git\ngComponentUtility\out\src\extension.js:4:58)

The message suggesting to check the developer console wasn't helpful in this case because the error wasn't being logged, but by debugging I've found the particular component it has an issue with and will try to figure out why its template is undefined. I'll submit a new issue if necessary.

**Comment by ipatalas** [comment]
Wow. This project you have there is a really good subject for this extension :-) so many different cases. Wondering what's gonna be next ;-) 
That's very good though. You're doing great job reporting all these issues. I wouldn't by able to find all that by myself. Thanks a lot!
