### ISSUE TITLE
Auto-detect AngularJS

### ISSUE THREAD

**Issue by ipatalas** [ipatalas/ngComponentUtility#18]
At the moment extension is activated on Html and TS files.
It's not perfect for several reasons. 
First of all it might get activated for a project which has nothing to do with Angular. It might not even be a web project.
Secondly for Angular projects when you open the project and the file that's opened is not Html nor TS then you won't have access to extension features right away.

To address this AngularJS detection should be implemented.

There are few places where to look for AngularJS dependency:
- [x] [package.json](https://github.com/preboot/angularjs-webpack)
- [x] [bower.json](https://github.com/angular/angular-seed)
- [x] [JSPM](https://github.com/bjanderson/jspm-angular-core), [#2](https://github.com/Oceanware/ng157es6jspm/blob/master/package.json)
- [ ] index.html (when using Angular from CDN)

**Comment by ipatalas** [comment]
First approach to AngularJS detection is implemented. So far it supports projects with Angular installed via npm, bower or JSPM.
If you have a situation where the extension does not start please use `Force enable ngComponents utility on this workspace` command for now and let me know about your project structure. 
I'd like this feature to cover vast majority of cases so please let me know if it doesn't work for you.

**Comment by chiptus** [comment]
can we define package.json location or can you check subfolders?

**Comment by ipatalas** [comment]
Well, it was supposed to be automatic so setting the path doesn't make much sense.
It's easier to just call the command mentioned above in my previous comment.

Let me know what structure do you have and where do you open your project in VSCode.
I'll try to improve auto-detection in next version.
