### ISSUE TITLE
Some features do not work when Angular root folder is not the workspace root

### ISSUE THREAD

**Issue by ipatalas** [ipatalas/ngComponentUtility#22]
Split from #20 (by @sergxp)

_So it does indeed look like the issue is solved and it's just my folder strucutre that's the issue. You can change this issue to fixed. I am still having difficulty with making this work with my folder structure._
![image](https://user-images.githubusercontent.com/28748653/36106342-b0e6f25e-0fdc-11e8-83ca-d9a27472d11e.png)
_My AngularJS resides in "app" and all of my SASS in "content" all of my templateUrl files begin with "app/.../../..." as soon as I change them to /src/app/.../.../" member intellisense starts working. But that would break my angular builds. Is there any workarounds for this?_

_PS: when I did change it to /src and played around with it a little, ctrl hover and peek definition worked great except for looking at object properties didn't show any information. Also when starting to type {{ I got an option for $ctrl but after that I did not receive any members. Funny enough though once I manually typed a member and ctrl hovered of it, it showed me correct intellisense._

**Comment by ipatalas** [comment]
To be honest I didn't expect such configuration but let's try to investigate this to find the best solution.

As a workaround (maybe even a final solution) there could be an option to define Angular root directory so that all paths are calculated relative to it.

First though I'd need a sample project to understand how it actually works.

Couple of questions:
- how do you define that Angular resides in a different directory? Maybe I could auto-detect that
- can you try executing **Code** inside your /src directory? (might wanna copy .vscode settings first) do all the features work then?
- how did you get this?
![image](https://user-images.githubusercontent.com/2623329/36116970-6d79e15a-1038-11e8-9921-5226e74c2887.png)
It only says my folder name without the _workspace_ in the brackets - is this a multi-root workspace? 
- Can you try "upgrading" the isolated project you shared with me on DropBox to achieve pretty much what you have in your real project? That would make it so much easier to understand it and provide a good solution. If you know any open source project with similar structure, that will do the job too.

**Comment by sergxp** [comment]
- how do you define that Angular resides in a different directory? Maybe I could auto-detect that
**We use gulp tasks to define that.**

- can you try executing Code inside your /src directory? (might wanna copy .vscode settings first) do all the features work then?
**I'm not sure what you mean...**

- how did you get this? It only says my folder name without the workspace in the brackets - is this a multi-root workspace?
**I created a workspace in VSCode**

- Can you try "upgrading" the isolated project you shared with me on DropBox to achieve pretty much what you have in your real project? That would make it so much easier to understand it and provide a good solution. If you know any open source project with similar structure, that will do the job too.
**https://www.dropbox.com/s/4lb1rc5o7ld6oxv/StaffWeb.zip?dl=0**

**Comment by ipatalas** [comment]
Regarding point 2 I meant to run Visual Studio Code inside your /src directory so that the workspace root will be correct to make sure nothing else breaks this.
Thanks for the code, I'll have a look on this later.

**Comment by sergxp** [comment]
So after I changed the workspace it worked! And that's good enough for me. If you still want to try figuring out how to make it work for my original structure, you can.

**Comment by ipatalas** [comment]
Glad that it worked. It shouldn't be that hard to implement an option to have custom Angular root (different than workspace root) so I think I'm gonna take a look at it anyway.

Regarding the intellisense it's probably a different issue, especially that it also happens when you run Code inside your /src directory. Can I reproduce it in the codebased you shared? If so then let me know how and I'll take a look at it as well.

**Comment by sergxp** [comment]
https://www.dropbox.com/s/4o77q2vjhrssv4u/issue20%28sergxp%29.zip?dl=0

If you open this folder, you should be able to reproduce the issue hopefully. Try peeking at $ctrl.currentLocation which should work. Then try typing {{$ctrl. and see if shows currentLocation in intellisense.

**Comment by ipatalas** [comment]
Well. Can't actually reproduce it:
![image](https://user-images.githubusercontent.com/2623329/36329880-dfea41da-1367-11e8-9a66-502f247d02f4.png)

Had to adjust template url first because it was incorrect:
![image](https://user-images.githubusercontent.com/2623329/36329925-09d785a2-1368-11e8-8ce5-cb3b30765bef.png)
