### ISSUE TITLE
Getting error when extension is rebuilding from the watch functionality

### ISSUE THREAD

**Issue by zatchgordon** [ipatalas/ngComponentUtility#24]
Getting error when extension is rebuilding from the watch functionality

If I change the "ngComponents.whatever" settings or manually "Refresh Angular components", everything is built without a problem: I get bindings, component auto-complete, the whole nine yards.

But if I go and edit an individual file and then save, everything still works except any changes are not seen in intellisense. For example if I added "randomVar" as a property, saved, and then tried intellisense in the template, ( $ctrl. ) randomVar won't show up as an option. Then when I manually "Refresh Angular components" the new binding for randomVar is available.

Opening the console I see this error 

[ipatalas.vscode-angular-components-intellisense]Path must be a string. Received undefined
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2844 

as well as

TypeError: Path must be a string. Received undefined
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2844 

and then, finally
[Extension Host] rejected promise not handled within 1 second
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:257 

below is an example of the code I'm running. 

This is all combined within one file.

```
class somethingModalController implements ng.IController {
    private resolve: {
        item: any
    };
    private dismiss: Function;
    private close: Function;
    private randomVar: number;

    /* @ngInject */
    constructor(
    ) { }

class SomethingModalComponent implements ng.IComponentOptions {
    static NAME: string = "somethingModal";
    controller: ng.Injectable<ng.IControllerConstructor> = somethingModalController;
    templateUrl: string = "app/features/something/something.component.html";
    bindings: any = {
        resolve: "<",
        close: "&",
        dismiss: "&"
    };
}


angular
    .module("app")
    .component(SomethingModalComponent.NAME, new SomethingModalComponent());
```

**Comment by zatchgordon** [comment]
Extra information for debugging

```
TypeError: Path must be a string. Received undefined
	at assertPath (path.js:7:11)
	at Object.normalize (path.js:311:5)
	at ComponentsCache.normalizePath (C:\Users\Zac Gordon\.vscode\extensions\ipatalas.vscode-angular-components-intellisense-0.7.3\out\src\utils\component\componentsCache.js:117:42)
	at idx.controllers.findIndex.c (C:\Users\Zac Gordon\.vscode\extensions\ipatalas.vscode-angular-components-intellisense-0.7.3\out\src\utils\component\componentsCache.js:48:62)
	at Array.findIndex (native)
	at ComponentsCache.<anonymous> (C:\Users\Zac Gordon\.vscode\extensions\ipatalas.vscode-angular-components-intellisense-0.7.3\out\src\utils\component\componentsCache.js:48:42)
	at Generator.next (<anonymous>)
	at C:\Users\Zac Gordon\.vscode\extensions\ipatalas.vscode-angular-components-intellisense-0.7.3\out\src\utils\component\componentsCache.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\Zac Gordon\.vscode\extensions\ipatalas.vscode-angular-components-intellisense-0.7.3\out\src\utils\component\componentsCache.js:3:12)
```

**Comment by ipatalas** [comment]
Thanks for reporting. I will take a look at it.

**Comment by ipatalas** [comment]
How did you get that extra info for debugging? That was really helpful to find the root cause. I thought it's impossible to get the extension call stack in production-mode extension.

Do you by any chance have any non-class controller in your project? For instance sth like this:
```JS
var myApp = angular.module('myApp',[]);

myApp.controller('DoubleController', ['$scope', function($scope) {
  $scope.double = function(value) { return value * 2; };
}]);
```

**Comment by zatchgordon** [comment]
Oh yeah I have tons of non-class controllers. I'm in the process of converting them all to classes slowly  but surely.

For the debugging I'm pretty sure I opened "Help > Toggle Developer Tools"
Or Ctrl/Cmd + shift + p "toggle developer tools" (same thing just different ways of opening it)

It opens, what looks like, a chrome debugger but it's for vscode. All the errors I posted came directly from the console.

**Comment by ipatalas** [comment]
Ok, that confirms my thoughts. I have none of them, that's why I never encountered that issue.
There is little more to be investigated because I found another problem with watch feature which is why it doesn't work for my project as well. 
I should be able to fix it all in upcoming days hopefully.

Before I release it I'll provide you with offline updated version to confirm it works if you don't mind.

**Comment by zatchgordon** [comment]
Sounds good to me. I don't know anything about how to install local/offline extensions so you may need to help me out with that but in the mean time, google is my friend.

**Comment by ipatalas** [comment]
Don't worry, I'll help you out. It's not difficult. Thanks.

**Comment by ipatalas** [comment]
Hi,

did some changes which should hopefully help. It works for me now in _production_ mode.
Please check it in your project:
[vscode-angular-components-intellisense-0.7.3.zip](https://github.com/ipatalas/ngComponentUtility/files/1952656/vscode-angular-components-intellisense-0.7.3.zip)

Installation steps:
1. Uninstall the extension first
2. Install extension from file using the following option:
![image](https://user-images.githubusercontent.com/2623329/39327493-7a69a6b8-4998-11e8-9760-d148fc05a191.png)

I've also enhanced logging in some places related to watch functionality to make it easier in future.
I see you already have verbose logging so it should just work.
When the extension is initialized you should get few of these:
![image](https://user-images.githubusercontent.com/2623329/39327666-f2ea8bac-4998-11e8-95e2-2a8eeb0c1d23.png)

Later on when you edit a controller file and save it it should go like this:
![image](https://user-images.githubusercontent.com/2623329/39327831-86c31c04-4999-11e8-9867-b71edef3bd63.png)

Let me know if you're getting these in the logs and if watch is working correctly or not.
If it doesn't we'll go deeper in next round :)

**Comment by zatchgordon** [comment]
I uninstalled the extension.
I downloaded the extension the link (0.7.3).
I unzipped it. 
I installed it from VSIX.

I got the same errors. I tried uninstalling and installing again and it made no difference.

```

console.ts:136 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:395
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
mainThreadExtensionService.ts:43 [ipatalas.vscode-angular-components-intellisense]Path must be a string. Received undefined
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:174
e._invokeHandler @ rpcProtocol.ts:159
e._receiveRequest @ rpcProtocol.ts:108
e._receiveOneMessage @ rpcProtocol.ts:90
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

```

mainThreadExtensionService.ts:43 [ipatalas.vscode-angular-components-intellisense]Path must be a string. Received undefined
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:174
e._invokeHandler @ rpcProtocol.ts:159
e._receiveRequest @ rpcProtocol.ts:108
e._receiveOneMessage @ rpcProtocol.ts:90
(anonymous) @ rpcProtocol.ts:33
(anonymous) @ rpcProtocol.ts:213
e.fire @ event.ts:140
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

  | e.$onExtensionRuntimeError | @ | mainThreadExtensionService.ts:43
-- | -- | -- | --
  | e._doInvokeHandler | @ | rpcProtocol.ts:174
  | e._invokeHandler | @ | rpcProtocol.ts:159
  | e._receiveRequest | @ | rpcProtocol.ts:108
  | e._receiveOneMessage | @ | rpcProtocol.ts:90
  | (anonymous) | @ | rpcProtocol.ts:33
  | (anonymous) | @ | rpcProtocol.ts:213
  | e.fire | @ | event.ts:140
  | (anonymous) | @ | ipc.net.ts:81
  | emitOne | @ | events.js:96
  | emit | @ | events.js:191
  | readableAddChunk | @ | _stream_readable.js:178
  | Readable.push | @ | _stream_readable.js:136
  | onread | @ | net.js:560


```

```

TypeError: Path must be a string. Received undefined
	at assertPath (path.js:7:11)
	at Object.normalize (path.js:311:5)
	at ComponentsCache.normalizePath (C:\Users\User\.vscode\extensions\ipatalas.vscode-angular-components-intellisense-0.7.3\out\src\utils\component\componentsCache.js:117:42)
	at idx.controllers.findIndex.c (C:\Users\User\.vscode\extensions\ipatalas.vscode-angular-components-intellisense-0.7.3\out\src\utils\component\componentsCache.js:48:62)
	at Array.findIndex (native)
	at ComponentsCache.<anonymous> (C:\Users\User\.vscode\extensions\ipatalas.vscode-angular-components-intellisense-0.7.3\out\src\utils\component\componentsCache.js:48:42)
	at Generator.next (<anonymous>)
	at C:\Users\User\.vscode\extensions\ipatalas.vscode-angular-components-intellisense-0.7.3\out\src\utils\component\componentsCache.js:7:71
	at Promise (<anonymous>)
	at __awaiter (C:\Users\User\.vscode\extensions\ipatalas.vscode-angular-components-intellisense-0.7.3\out\src\utils\component\componentsCache.js:3:12)
	at ComponentsCache.onControllerChanged (C:\Users\User\.vscode\extensions\ipatalas.vscode-angular-components-intellisense-0.7.3\out\src\utils\component\componentsCache.js:46:45)
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:344)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:451:481
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:344)
	at e.$onFileEvent (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:793)
	at e._doInvokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:395)
	at e._invokeHandler (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:113)
	at e._receiveRequest (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:559:237)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:559:6)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:558:75
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:929
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:30
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:344)
	at Socket.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:143:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)


```

**Comment by zatchgordon** [comment]
The successful logs I received look like this

```
[Extension Host] [ngComponents] HTML stats [files=89, glob=1.93 s, parse=284 ms]
console.ts:136 [Extension Host] [ngComponents] Controller stats [files=47, glob=1.15 s, parse=304 ms, analyze=51 ms, total=1.5 s]
console.ts:136 [Extension Host] [ngComponents] Component stats [files=58, glob=841 ms, parse=233 ms, analyze=259 ms, total=1.33 s]
console.ts:136 [Extension Host] [ngComponents] Route stats [files=0, glob=1.05 s, parse=25 μs, analyze=8.98 μs, total=1.05 s]
```

I don't see any logs for "setting up watch for **/*Component.ts"

Also, here are my settings

```
ngComponents.componentGlobs": [
        "**/*.{component,directive}.ts"
    ],
    "ngComponents.controllerGlobs": [
        "**/*.{component}.ts"
    ],
    "ngComponents.htmlGlobs": [
        "**/*.{component,directive}.html"
    ],
    "ngComponents.routeGlobs": [
        "*.router.ts"
    ],
    "ngComponents.goToDefinition": [
        "template",
        "controller",
        "component"
    ],
    "ngComponents.controller.publicMembersOnly": false
```

As I said, I'm in the process of converting controllers and directives into components and as you can see in the settings I use the fileName.component.ts structure or fileName.directive.ts instead of the fileNameComponent.ts structure. I'm just throwing things out there to see if any of this helps.

**Comment by ipatalas** [comment]
Figured out it might be some caching issue. Version is in the path, so I did version bump so that it no longer hits the same place.

[vscode-angular-components-intellisense-0.7.4.zip](https://github.com/ipatalas/ngComponentUtility/files/1952879/vscode-angular-components-intellisense-0.7.4.zip)

**Comment by zatchgordon** [comment]
Good news and some bad news.... 

The good news is I'm not getting any errors. 
The logging is correctly letting me know it detected a change in the component/controller/template where I last saved.

The bad news is my intellisense (after typing "$ctrl.") is not updating to the latest information.

**Comment by ipatalas** [comment]
Ok. At least a step forward.
Can you try to isolate a single component which doesn't work along with its angular registration.
Strip out any business logic obviously.
Put it to a separate empty folder as a new project and try again there.
You might wanna put a fake package.json with angular dependency so that the project is correctly recognized. Alternatively you can use **Mark as angular project** command. It should force the extension to load even if it's not a proper project.

If you can repeat the issue there please share that isolated code with me. It will be way easier if I can reproduce the problem on my side.
Otherwise I will have to log pretty much every single line to see when it breaks.
If you can't or don't want to I can guide you how to debug vscode extensions and I could give you some info where to look to help me out.
Whatever you prefer is fine for me. Gotta go now. Leaving tomorrow and I'll be back Saturday evening or Sunday. Take your time to make the decision and thanks for helping me investigating this issue so far.

**Comment by zatchgordon** [comment]
I created a repository that seems the be seeing the same thing: no errors but intellisense is not updating.

https://github.com/zatchgordon/ngComponentUtilityBug
npm install
npm start (if you want to run it)
add the ng1.5 component utility extension
Change (and save) the home.component.ts properties and then go into home.component.html and try to use intellisense.

**Comment by zatchgordon** [comment]
I didn't see any change after that. I tried in my work project as well as the repo I sent in the other comment.

1. open project
2. npm install
3. open home.component.html
4. type {{ $ctrl. }} (after the period, intellisense kicks in and I see "coolio" and "helloWords"
5. choose neither
6. open home.component.ts
7. change "coolio" to be "whatever"
8. save home.component.ts
9. open home.componet.html
10. in {{ $ctrl. }} delete the period and then type the period again to kick in intellisense 

The intellisense options are still "coolio" and "helloWords" while I would expect the options to be "whatever" and "helloWords".

**Comment by ipatalas** [comment]
Do you uninstall the extension before installing it from VSIX?

Anyway. I think it might be some caching issue like last time when it didn't work until I bumped the version so please have a look again with this:
[vscode-angular-components-intellisense-0.7.5.zip](https://github.com/ipatalas/ngComponentUtility/files/1962127/vscode-angular-components-intellisense-0.7.5.zip)

**Comment by ipatalas** [comment]
Glad it worked. Thanks a lot for your help here. I will benefit from this fix as well.

Just made a release. Something is telling me it might be a problem since you have 0.7.5 installed now.
I would suggest uninstalling the extension again first. 
Then I would clean your `C:\Users\user\.vscode\extensions\` from any folders starting with `ipatalas.vscode-angular-components-intellisense-` (all versions if there are more).
