### ISSUE TITLE
Controller members no longer work

### ISSUE THREAD

**Issue by sergxp** [ipatalas/ngComponentUtility#29]
Since recent updates, the intellisense for controller members has stopped working. I can still get component bound members to show as well as components `(<componentname>).` But things like $ctrl.member no longer work.

**Comment by sergxp** [comment]
I figured out how to make it work by force enabling the extension. Even though it was finding components before, I'm not sure why that seems to fix it.

**Comment by ipatalas** [comment]
That's interesting. It works just fine for me.
Have you tried just executing `Refresh components cache` command before force enabling the extension?

Can't figure out how it could make the difference. Force enable only allows to actually activate the extension when Angular cannot be auto-detected in the workspace. If it's not detected then nothing should work at all. All commands are bound to a message saying that Angular was not detected and you should try force enable.
Intellisense can not simply work partially. Can you try removing force enable and checking again if the problem still occurs?
