### ISSUE TITLE
literal constant name is used for component suggestions

### ISSUE THREAD

**Issue by xsintill** [ipatalas/ngComponentUtility#3]
extension should extract value of constant when it's used for component registration and use that as it's suggestion instead of the literal constantname.

see screenshot for example of the way the component is registered and the way it is suggested and when suggestion used.
![image](https://cloud.githubusercontent.com/assets/5768071/22780424/f9e8e29a-eebe-11e6-816e-aff0557394e8.png)

**Comment by ipatalas** [comment]
Do you have this constant defined in the same file or is it imported?

**Comment by ipatalas** [comment]
Fixed in 0.6.0
