### ISSUE TITLE
Is there or will there be a visual studio 2017/2019 version?

### ISSUE THREAD

**Issue by FreeFrags** [ipatalas/ngComponentUtility#34]
Is there or will there be a visual studio 2017/2019 version? This utility looks great!

**Comment by ipatalas** [comment]
Hey there,

happy to hear that but having that for full VS is a different story.  It cannot be just ported. VSCode extensions are written in TypeScript while VS extensions are written in C#. The API is totally different as well. That means huge effort so I do not have such a plan but maybe somebody else has.

**Comment by FreeFrags** [comment]
Keep up the nice work! And thank you for your reply!
