### ISSUE TITLE
components which are registered with static class fields in typescript won't be picked up in the cache

### ISSUE THREAD

**Issue by xsintill** [ipatalas/ngComponentUtility#4]
Expected to have llq-ocs-list as a component in the cache but it's not in there. This probably has to do with the component having been registered with a static class field in the controller class

see image for example:

![image](https://cloud.githubusercontent.com/assets/5768071/22781118/713caed8-eec1-11e6-8c9a-bf29232ee5ab.png)

**Comment by ipatalas** [comment]
Thanks for reporting. Such feature is not implemented yet. Quite frankly we hardcore those names in our project so we didn't need it.
It shouldn't be very difficult to implement it, I'll think about it in next version. For performance reasons though I will have to limit it to defining those constants or statics in the same file.
We use Typescript Compiler API to parse source files and parsing whole project might not be the best option.

**Comment by ipatalas** [comment]
Fixed in 0.6.0
