### ISSUE TITLE
improved component lookup

### ISSUE THREAD

**Issue by FDIM** [ipatalas/ngComponentUtility#5]
Hi, this is extremely useful!

What would it take to make this format work:
```
var MyComponent = {
    /* other settings */
    bindings: {
        config: '<',
        data: '<'
    }
};
angular.module('app').component('exampleComponent', MyComponent);

``` 

I mean a static variable instead of an object? 

If you could give me any pointers I can contribute

**Comment by ipatalas** [comment]
This feature is on my list but I prioritize things which I have on project I work on first. Sorry for that :)
That would be great if you could help. It's an easy feature so a good starter :)

First of all get familiar with Typescript AST. There is a great site for this: https://astexplorer.net/#/gist/f49f9c49f96e984e64c623509d4b2fe6/df9545ee379281778408a5b44435fe886ea826f8
(already prefilled with the code above)

Then you can have a look at https://github.com/ipatalas/ngComponentUtility/blob/master/src/utils/component.ts#L47

It's where the AST traversing begins. It's strictly for component files, so just look around to get a a feeling about it.

This specific case should be actually easy to implement. What I would've done is to traverse all _Identifier_ nodes (that's the one that holds the **MyComponent** variable name), cache them for the time of parsing this file and then look them up again in [this](https://github.com/ipatalas/ngComponentUtility/blob/master/src/utils/component.ts#L55) line when there is such a need. _Identifier_'s parent is a _VariableDeclaration_ node (also for **let** or **const** which is a bonus) which holds the _ObjectLiteralExpression_ which we're looking for.

Currently this line assumes it's always an object literal which is obviously wrong. My bad there isn't any _if_ statement to verify if it's correct. I would put a helper method there to get the object literal no matter where it is. For now we have these two cases but I also plan to implement it in a way that lets you define component configuration in a separate file (see #2). This is slightly more complicated but still doable.

If you need further assistance, just let me know. I'll answer as soon as I can.

**Comment by ipatalas** [comment]
Check out https://github.com/ipatalas/ngComponentUtility/commit/5ebd2e71971eca47da872699898042b02adc8710

I just made a very quick implementation of pretty much the same feature but for component name. Feel free to use it. Made it very quickly, gonna review and merge later but it should be enough for you to get started. The code will be very similar.

**Comment by FDIM** [comment]
Thanks, I'll give it a go in the weekend

**Comment by ipatalas** [comment]
Hi @FDIM 

"Unfortunately" I couldn't resist and implemented it myself :) Need some more testing but new release should come by the end of this weekend.

**Comment by FDIM** [comment]
Even though I am a bit sad, this is great! :)

I looked at the code a bit, and from what I can see the location of `module.component('<name>', <config>)` doesn't matter right? It just goes through all the children looking for a component call with 2 arguments.

I mean, this should just work as well:

```
var ListComponent = {
  bindings: {
    type: '<'
  },
  template: require('./list.partial.html'),
  controller: 'ListController'
};

module.exports = function (module) {
  require('./list.controller')(module);
  module.component('list', ListComponent);
}
``` 

The above is I 'think' a typical format when using webpack/browserify

**Comment by ipatalas** [comment]
Well, you don't have to be sad. I can provide you a list of features that seem to have value. Feel free to implement any of them or pick your own if you have an idea :) I'll be happy to accept a PR.

Regarding your observations, you're right. It's exactly like that. It's not perfect, but good enough and was pretty easy to implement. The component you provided works just fine :)

**Comment by ipatalas** [comment]
Fixed in 0.6.0 - also allowing to use static class properties for configuration like:

```Typescript
class ComponentController {
	constructor() {
	}

	public static componentName: string = 'staticComponentName';
	public static templateUrl = 'template.html';

	public static componentConfiguration = {
		templateUrl: ComponentController.templateUrl,
		bindings: {
			config: '<',
			data: '<'
		}
	}
}

angular.module('app').component(ComponentController.componentName, ComponentController.componentConfiguration);
```

**Comment by FDIM** [comment]
I was just joking about being sad - I am very glad to see this ready! :) Gonna give this a go on a big project at work, we have lots of components there and it's much harder to keep track of everything compared to the things I do after work. Thanks!

**Comment by ipatalas** [comment]
Yeah, I know.. but I wasn't joking about implementing a feature of your own ;)

Let me know how it performs. I use it on a project with almost 300 components and it works fine.
