### ISSUE TITLE
Plugin No longer runs

### ISSUE THREAD

**Issue by TrikinCurt** [ipatalas/ngComponentUtility#7]
I had installed the plugin, it worked as expected.  I reloaded my workspace and the UI disappeared.  Concerned I tried running "Refresh Component Cache", it still shows up as an option to run but I receive extension.refreshAngularComponents.extension not found

I confirmed it is in my directory ~/vscode/extensions that ipatalas.vscode-angular-components-intellisense-0.6.1 does exist.

vscode 1.11.2 on a mac.

**Comment by ipatalas** [comment]
Need more info to help you.

Did it work before updating vscode to 1.11.2?

Can you turn on Developer Tools console (Help -> Toggle Developer Tools or `Developer: Toggle Developer Tools` command) and then reload your workspace and see if you're getting any errors in the console? If so please paste them here.

Based on the error you're getting while trying to refresh the components it seems like the plugin did not initialize correctly. Maybe it's naive but have you tried uninstalling it and installing again?

**Comment by ipatalas** [comment]
@TrikinCurt anything?

**Comment by TrikinCurt** [comment]
Sorry for the delay, I had installed/reinstalled more than once with no change.  It is now working after VS Code itself had an update, unsure if there was a real issue with compatibility or if it was simply triggered by that update.  Either way, I will close it.  Thanks for the help!

**Comment by ipatalas** [comment]
I wasn't able to figure out the problem back then but I think now I know what was the problem.
See my comment here: https://github.com/ipatalas/ngComponentUtility/issues/2#issuecomment-303217702
I will put that improvement on my list to avoid such problems in future.
