### ISSUE TITLE
Error analyzing controller where a method parameter has no type

### ISSUE THREAD

**Issue by stogle** [ipatalas/ngComponentUtility#8]
If a controller contains a method with a parameter that does not have a type, the following error is logged:

> [ngComponents] There was an error analyzing .\src\test.controller.ts.
> Please report this as a bug and include failing file if possible (remove or change sensitive data).
> 
> TypeError: Cannot read property 'getText' of undefined

For example, a controller with the following method produces the error:

    public $onChanges(changesObj) {
        ...
    }

If I add a type to the parameter, it no longer produces the error:

    public $onChanges(changesObj: ng.IOnChangesObject) {
        ...
    }

My guess is the TypeError comes from this line: https://github.com/ipatalas/ngComponentUtility/blob/master/src/utils/controller/controllerParser.ts#L45

**Comment by ipatalas** [comment]
Fixed in 0.6.4

Thank you for great report.
