### ISSUE TITLE
Error analyzing route when state config has a typecast

### ISSUE THREAD

**Issue by stogle** [ipatalas/ngComponentUtility#9]
If a route file declares a state with a config that is a typecast object literal, the following error is logged:

> [ngComponents] There was an error analyzing .\src\test.route.ts.
> Please report this as a bug and include failing file if possible (remove or change sensitive data).
> 
> TypeError: Cannot read property 'find' of undefined

For example, a route file with the following declaration produces the error:

    $stateProvider
        .state("test", {
            url: "/test"
        } as ng.ui.IState)

If I remove the typecast, it no longer produces the error:

    $stateProvider
        .state("test", {
            url: "/test"
        })

My guess is the TypeError comes from this line: https://github.com/ipatalas/ngComponentUtility/blob/master/src/utils/route.ts#L63

**Comment by ipatalas** [comment]
Fixed in 0.6.4

Thank you for great report.
